version: "3.8"

services:
  influxdb:
    container_name: influxdb
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb:/var/lib/influxdb2
      - ./conf/influxdb:/etc/influxdb2
    restart: always

  telegraf:
    container_name: telegraf
    image: telegraf
    network_mode: "host"
    volumes:
      - ./conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
      - mqtt
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana
    user: "0"
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./log/grafana:/var/log/grafana
    depends_on:
      - influxdb
    restart: always

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    user: "0"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./conf/mqtt/:/mosquitto/config/
      - ./data/mqtt/:/mosquitto/data/
      - ./log/mqtt/:/mosquitto/log/
    restart: always

  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tfg_iot
      POSTGRES_USER: tfg_user
      POSTGRES_PASSWORD: tfg_password_seguro_2024
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tfg_user -d tfg_iot"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: tfg_iot
      DB_USER: tfg_user
      DB_PASSWORD: tfg_password_seguro_2024
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: wlU1zhuHiHp_BAzRYdBY0zGebWOKS4kF-j413vNg4qknVsXqaiLPJKii9UXOIK3EOTZt5JiGudanARcSCaG5cQ==
      INFLUX_ORG: GranaSAT
      INFLUX_BUCKET: NeutronSource
      JWT_SECRET: mi_secreto_super_seguro_cambiar_en_produccion_123456
      JWT_EXPIRES_IN: 24h
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: gilrubenmartin@gmail.com
      SMTP_PASS: ogjrrxmkgonuhbsl
      MQTT_HOST: mqtt
      MQTT_PORT: 1883
    depends_on:
      postgres:
        condition: service_healthy
      influxdb:
        condition: service_started
    restart: always

  frontend:
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001/api   #CAMBIAR CUANDO TENGA IP PARA DESPLEGAR
    container_name: frontend
    build: ./frontend
    ports:
      - "3002:3000"
    depends_on:
      - backend
    restart: always