
[[inputs.mqtt_consumer]]
  #servers = ["tcp://mqtt_rad:1883"]  # Your WSL broker. Tiene que ser la IP del WSL, con el comando ipconfig se obtiene
  topics = ["test", "iot/#", "Neutron_Source", "Medidas_Instrumentacion"] # Los env�os en MQTT tienen asociado un topic a los cuales te puedes suscribir
  data_format = "influx"  # Changed to influx.
  servers = ["tcp://mqtt.granasat.space:1883"]

[[outputs.influxdb_v2]]
  urls = ["http://influxdb_rad:8086"]  # Tiene que ser la IP del WSL, con el comando ipconfig se obtiene
  token = "Y2DScBBA2OUWac5EIy3ePKuWNtaElPerCl3bqa0tTXNGzL65NNYDMdCMi5RbDLqe9BhVprjl5FoIKjjUqSjwKg=="
  organization = "GranaSAT"
  bucket = "NeutronSource"


#fEbHJjtGuX28Y8nbGp6JCIoRPzHimHBc-lR08haWQzpfE5b2MB-cldIoYihKLbPDX-U3HypDJ5zD0kFPx4oPQA==