
[[inputs.mqtt_consumer]]
  servers = ["tcp://mqtt_rad:1883"]  # Your WSL broker. Tiene que ser la IP del WSL, con el comando ipconfig se obtiene
  topics = ["test", "iot/#", "Neutron_Source", "Medidas_Instrumentacion"] # Los env�os en MQTT tienen asociado un topic a los cuales te puedes suscribir
  data_format = "influx"  # Changed to influx.

[[outputs.influxdb_v2]]
  urls = ["http://influxdb_rad:8086"]  # Tiene que ser la IP del WSL, con el comando ipconfig se obtiene
  token = "wlU1zhuHiHp_BAzRYdBY0zGebWOKS4kF-j413vNg4qknVsXqaiLPJKii9UXOIK3EOTZt5JiGudanARcSCaG5cQ=="
  organization = "GranaSAT"
  bucket = "NeutronSource"
